// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs3rw2Bk--giTjeQsLLfwmBNghJQ1BN5Y',
    appId: '1:323672625777:web:f8f55a741ad406d19bc1d0',
    messagingSenderId: '323672625777',
    projectId: 'animal-cage',
    authDomain: 'animal-cage.firebaseapp.com',
    databaseURL: 'https://animal-cage-default-rtdb.firebaseio.com',
    storageBucket: 'animal-cage.firebasestorage.app',
    measurementId: 'G-R59CDKSKZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe5Pe1qRcFvxvWRjC9fqp0aQm5YwUss04',
    appId: '1:323672625777:android:043e285f1ee09cc29bc1d0',
    messagingSenderId: '323672625777',
    projectId: 'animal-cage',
    databaseURL: 'https://animal-cage-default-rtdb.firebaseio.com',
    storageBucket: 'animal-cage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp_PZI7LkHG_LgYh0vWiknxeF115JoKJg',
    appId: '1:323672625777:ios:912564d13fef4da79bc1d0',
    messagingSenderId: '323672625777',
    projectId: 'animal-cage',
    databaseURL: 'https://animal-cage-default-rtdb.firebaseio.com',
    storageBucket: 'animal-cage.firebasestorage.app',
    iosBundleId: 'com.example.joki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp_PZI7LkHG_LgYh0vWiknxeF115JoKJg',
    appId: '1:323672625777:ios:912564d13fef4da79bc1d0',
    messagingSenderId: '323672625777',
    projectId: 'animal-cage',
    databaseURL: 'https://animal-cage-default-rtdb.firebaseio.com',
    storageBucket: 'animal-cage.firebasestorage.app',
    iosBundleId: 'com.example.joki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs3rw2Bk--giTjeQsLLfwmBNghJQ1BN5Y',
    appId: '1:323672625777:web:e59a1ee2deb3d61b9bc1d0',
    messagingSenderId: '323672625777',
    projectId: 'animal-cage',
    authDomain: 'animal-cage.firebaseapp.com',
    databaseURL: 'https://animal-cage-default-rtdb.firebaseio.com',
    storageBucket: 'animal-cage.firebasestorage.app',
    measurementId: 'G-P8GJ0R0FZH',
  );
}
